version: "3"

services:
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: coffeeshop
            MINIO_ROOT_PASSWORD: coffeeshop123
        volumes:
            - minio_data:/data
        command: server /data --console-address ":9001"
        restart: unless-stopped

volumes:
    minio_data:
